modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="theshapeshifterbyxboxscontentnw"
version="1.0.0"
displayName="TheShapeShifter(ByXbox'sContentNW)"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="PC, MCreator"

[[dependencies.theshapeshifterbyxboxscontentnw]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.theshapeshifterbyxboxscontentnw]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

